### ISSUE TITLE
elasticsearch demos should set Java VM heap size

### ISSUE THREAD

**Issue by w0pr** [sixeyed/presentations#3]
Docker files v3.yml and v4 yml should include the following line in elasticsearch service:

 **- "ES_JAVA_OPTS=-Xms512m -Xmx512m"**
 ```
elasticsearch:
    image: sixeyed/elasticsearch:5.6.11-nanoserver-sac2016
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - app-net
```
